; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico

framework = arduino

lib_ignore = 
    symlink://lib



build_src_filter = +<testing.cpp> ;+<main.cpp>

[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino

board_build.mcu = esp32

; lib_ignore = 
;     rcj_vision26


build_src_filter = +<kicker_test.cpp> ;+<main.cpp>
monitor_speed = 9600

;upload: pio run -t upload -e upesy_wroom
;pio device monitor